### PR TITLE
LPS-162818 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LPS-162818

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:sf

**Review by joshchong — CHANGES_REQUESTED** [review]
Hey Brooke, please see comments for changes. After making them you can push up this test. Thanks!

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:forward

**Pull request closed without merging**
