### PR TITLE
LPS-84703 journal-test: build.gradle

### PR DESCRIPTION
**Pull request by brandizzi**
Hello Josh! Hope you have a great Christmas :smile: :christmas_tree: 

I am having a problem with the test [Search#SearchMessageBoardsThread](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase#L987-L990). We have made some changes in the journal article indexer, and then the string used to get an empty-results search does match the value used in the test. I've written an explanation of what is going [on in the ticket](https://issues.liferay.com/browse/LPS-84703?focusedCommentId=1651394&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1651394).

As I explained in the ticket, I _do believe_ this behavior change is not a bug and is acceptable. So I'd like to change the test to use another string that does not break it when looking for a no-result. Could you check that? Thanks!

cc @arboliveira

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:search

**Comment by arboliveira** [comment]
@brandizzi @joshchong https://issues.liferay.com/browse/LPS-88777

**Comment by joshchong** [comment]
Resent here with functional test updates: https://github.com/brandizzi/liferay-portal/pull/580

**Pull request closed without merging**
