### PR TITLE
master-qa-52699

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-52699

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf:norebase

**Comment by suilin** [comment]
ci:test:search-solr:norebase

**Comment by xbrianlee** [comment]
@suilin Nice job on this! One minor change. Can we turn the curls into targets in the Elasticsearch & Solr build scripts? We can pass in the variables as params.

**Comment by suilin** [comment]
@xbrianlee Thank you, I will do it and resend it to you.

**Pull request closed without merging**
