### PR TITLE
LPS-159142 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LPS-159142

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:search:nocompile

**Comment by joshchong** [comment]
@brookedalton can you analyze these results?

**Comment by brookedalton** [comment]
Hi @joshchong yea I need to make an additional change, I'll push it up soon!

**Comment by brookedalton** [comment]
ci:test:search:nocompile

**Comment by brookedalton** [comment]
ci:test:search:nocompile

**Comment by brookedalton** [comment]
Hi @joshchong, the changes I made fix Search#NavigateToSearchResultsViaURL and ClassicSearch#SearchTwiceScopeLetUserChoose

**Comment by joshchong** [comment]
ci:forward

thanks @brookedalton

**Pull request closed without merging**
