### PR TITLE
LPS-183128 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LPS-183128

### CODE REVIEW

**Comment by joshchong** [comment]
@brookedalton nice work!

Can you make the following changes:
- Rename the testcase files to SearchFacets?
- Remove the manual tear down steps in all files. i.e. the `else` block in the `tearDown`

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by joshchong** [comment]
@brookedalton can we rename SearchAssetType.testcase to SearchFacets.testcase? This is keeping in line with the official naming of those type of widgets as seen in the docs here: https://learn.liferay.com/w/dxp/using-search/search-pages-and-widgets/search-facets

All of the tests that primarily test the widgets listed in that doc page should show up in SearchFacets.testcase

**Comment by brookedalton** [comment]
Hey @joshchong I created a  SearchFacets.testcase for tests that deal with the different search widgets and another file called SearchAssetType.testcase for our tests that search for an asset type, eg: Search#SearchWebContent, Search#SearchUser, and Search#SearchBlogsEntry

**Comment by joshchong** [comment]
@brookedalton, ooh sorry I completely missed that. However, I think I prefer if we kept the asset type tests in Search.testcase actually. I get that they are all logically similar, but they aren't really testing a separate product or feature to warrant having their own testcase file.

**Comment by brookedalton** [comment]
I was thinking since there are so many asset tests that perform similarly, they can be separated into a search asset file for easier navigation and would be easier for non-search QA members to read/navigate

**Comment by joshchong** [comment]
I was actually thinking it would be easier to navigate / find those tests if it was in the same file since it's not immediately obvious that they would be located somewhere else given they aren't really testing anything different. Also all of our search testcases are logically organized by features / product, but this one wouldn't be so it would feel a bit inconsistent

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by joshchong** [comment]
resent here: https://github.com/joshchong/liferay-portal/pull/698

**Comment by joshchong** [comment]
ci:forward

**Pull request closed without merging**
