### PR TITLE
LRQA-59354 | master

### PR DESCRIPTION
**Pull request by joshchong**
https://issues.liferay.com/browse/LRQA-59354

7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/30720
7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/30719

### CODE REVIEW

**Comment by joshchong** [comment]
ci:forward

**Comment by joshchong** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by kenjiheigel** [comment]
Just conducting another test. It should fail out we think. Please ignore the result though.

**Pull request closed without merging**
