### PR TITLE
Elasticsearch Server Version Bump Test | master

### PR DESCRIPTION
**Pull request by joshchong**

### CODE REVIEW

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:stop

**Comment by xbrianlee** [comment]
test

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:search-jdk11

**Comment by joshchong** [comment]
ci:test:search-jdk11

**Comment by joshchong** [comment]
ci:test:workflow

**Comment by joshchong** [comment]
ci:test:commerce

**Comment by lipusz** [comment]
ci:close

**Comment by lipusz** [comment]
Re-running workflow suite with the interim changes based on the response from Elastic Support at https://github.com/lipusz/liferay-portal/pull/327

**Pull request closed without merging**
