### PR TITLE
Sidecar Latest Branch Test

### PR DESCRIPTION
**Pull request by joshchong**

### CODE REVIEW

**Comment by joshchong** [comment]
ci:test:sf

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:search-es7

**Comment by joshchong** [comment]
ci:test:search-solr

**Comment by joshchong** [comment]
Hey @tinatian, I analyzed the results and it there are two failures that are unique to this PR, both of which are failing in `ci:test:relevant` as well as the other suites.

1. There are several failures in **modules-semantic-versioning-jdk8**, but the one that is unique to this PR is failing with the following:

```
     [exec] Execution failed for task ':apps:portal-search-elasticsearch7:portal-search-elasticsearch7-api:baseline'.
     [exec] > A failure occurred while executing com.liferay.gradle.plugins.baseline.internal.work.BaselineWorkAction
     [exec]    > org.gradle.api.GradleException: Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.portal.search.elasticsearch7.api-2.0.8.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.portal.search.elasticsearch7.api/2.0.7/91153c8f7cdd5062940288de238b2e24ab644875/com.liferay.portal.search.elasticsearch7.api-2.0.7.jar
```
[Full console log](https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/339698/AXIS_VARIABLE=0,label_exp=!master/consoleText)

Running baseline locally, it looks like semver is expecting a major version bump in `com.liferay.portal.search.elasticsearch7.api` from `2.0.8` to `3.0.0`. Does this seem correct? @arboliveira

2. There is a test compile failure within the **modules-unit-jdk8** batch failing with the following:

```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/test/java/com/liferay/portal/search/elasticsearch7/internal/connection/ElasticsearchConnectionManagerTest.java:303: error: cannot find symbol
     [exec] 			EmbeddedElasticsearchConnection.CONNECTION_ID
     [exec] 			                               ^
     [exec]   symbol:   variable CONNECTION_ID
     [exec]   location: class EmbeddedElasticsearchConnection
```
[Full console log](https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/377941/AXIS_VARIABLE=0,label_exp=!master/consoleText)

I confirmed that these two failures are not occurring on the same upstream hash elsewhere. Can you take a look?

**Comment by tinatian** [comment]
@joshchong Thanks for catching it! They are caused by recent changes on es7, I already pushed two commits to fix them, please see https://github.com/joshchong/liferay-portal/pull/267

**Comment by joshchong** [comment]
@tinatian got it, I'll analyze those new results. Thanks!

**Pull request closed without merging**
