### PR TITLE
LPS-163931 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LPS-163931

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:search:nocompile

**Comment by joshchong** [comment]
@brookedalton when testing single tests, can you either test it locally or scope a PR to run it individually instead of running the full search suite?

**Comment by brookedalton** [comment]
Test passed here: https://github.com/brookedalton/liferay-portal/pull/127#issuecomment-1260117466

**Comment by joshchong** [comment]
ci:forward

**Pull request closed without merging**
