### PR TITLE
LPS-182458 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LPS-182458

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:search:nocompile

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by joshchong** [comment]
@brookedalton nice work! Just one thing, can you remove the `test.name.skip.portal.instance` for this test? I believe that was added in just to perform a reindex which the test isn't doing anymore. You can push it up right away after that change.

**Comment by brookedalton** [comment]
Hey @joshchong, is it ok if we keep it? I'm deleting the "Provided by Liferay" document folder since it was affecting this test with the changes I made but some of our other tests rely on those documents.

**Comment by joshchong** [comment]
@brookedalton, it should be okay to delete those documents since the test would be running on a virtual instance and not affect other tests running on separate instances.

**Pull request closed without merging**
