### PR TITLE
LRQA-62593 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LRQA-62593

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:sf

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
hey @brookedalton, let me know if the search suite failures are relevant in either this PR or in 7.3 https://github.com/joshchong/liferay-portal-ee/pull/202#issuecomment-719064336. No need to analyze the ci:test:relevant results.

**Comment by brookedalton** [comment]
Hey @joshchong ! For master the only new errors I see are portal kernel semantic version issues which wouldn't be related and no new errors for 7.3

**Pull request closed without merging**
