### PR TITLE
LPS-194324

### PR DESCRIPTION
**Pull request by CaiocSiqueira**
https://liferay.atlassian.net/browse/LPS-194324

PASSED Testing on: https://github.com/CaiocSiqueira/liferay-portal/pull/59

### CODE REVIEW

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by joshchong** [comment]
hey @CaiocSiqueira, can you add `@description = "This is a use case for LPS-177665."` to the top of the test and rename the test to `ReindexSearchTuningWithConcurrentExecutionMode`?

after that you can just ci:forward. Thanks!

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:forward

**Pull request closed without merging**
