### PR TITLE
[Sidecar]LPS-106592-LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:search

**Comment by tinatian** [comment]
ci:test:search-es7

**Comment by tinatian** [comment]
ci:test:search-solr

**Comment by joshchong** [comment]
Hey @tinatian, I'm seeing one new unique failure in the relevant run. I was able to reproduce this failure locally with this branch but not at head. Can you take a look?

`ElasticsearchConnectionManagerTest.testActivateMustNotChangeAnyConnection` is failing with Elasticsearch 7 with the following:
```
org.mockito.exceptions.verification.NeverWantedButInvoked: 
_embeddedElasticsearchConnection.connect();
Never wanted here:
-> at com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManagerTest.verifyNeverCloseNeverConnect(ElasticsearchConnectionManagerTest.java:412)
But invoked here:
-> at com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManager.activate(ElasticsearchConnectionManager.java:270)
```
[See jenkins result](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/373768/AXIS_VARIABLE=0,label_exp=!master/testReport/com.liferay.portal.search.elasticsearch7.internal.connection/ElasticsearchConnectionManagerTest/testActivateMustNotChangeAnyConnection/).

**Comment by tinatian** [comment]
@joshchong I have to talk with Bryan about this. This test was ignored and reactivated recently by Bryan, what it is trying to test actually conflicts with what I did. I will send you a new pull after talked to him.

Thanks for catching all these! 

Tina.

**Pull request closed without merging**
