### PR TITLE
LRQA-73676 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LRQA-73676

### CODE REVIEW

**Comment by joshchong** [comment]
@brookedalton I'm a bit confused by this change. Won't this remove the test from the upstream job completely?

**Comment by brookedalton** [comment]
@joshchong yes it would. The options I saw were to either remove it from the upstream job completely or add in the jdk11 functional batch into the upstream-dxp job. These are the only 2 functional tests that are run with JDK11 so I thought removing them from the upstream job would be a better solution since these tests are run daily in the search canary. If you think that these should be added into the upstream job then I can make those changes also.

**Comment by joshchong** [comment]
@brookedalton, oh I see. Yeah I think we should add the jdk11 batch to the upstream job even if they're only running these two tests. This allows people outside our team who analyze that job to catch issues as well especially in instances where the upstream suite is used to test PRs.

**Comment by brookedalton** [comment]
ci:test:upstream-dxp:nocompile

**Comment by joshchong** [comment]
@brookedalton let's try just using `${test.batch.run.property.query[functional-tomcat90-mysql57-jdk11_open][search]}` for the PQL to simplify things and to be clear what we're trying to do. Also we should be okay with just running the `functional-tomcat90-mysql57-jdk11_open` batch in the test run.

**Comment by brookedalton** [comment]
ci:test:upstream-dxp:nocompile

**Comment by joshchong** [comment]
ci:test:upstream-dxp

**Comment by joshchong** [comment]
@brookedalton reminder to scope to just the `functional-tomcat90-mysql57-jdk11_open` batch when testing this. The [last run](https://test-1-1.liferay.com//userContent/jobs/test-portal-testsuite-upstream%28master%29/builds/591/jenkins-report.html) used ~57 times more server resources than our typical search canary :grimacing:

**Comment by brookedalton** [comment]
Hi @joshchong, I was trying to see if the test was also being run with jdk8 and it is. I think removing the `portal.upstream == quarantine` from the test and also from functional-tomcat90-mysql57-jdk11_open will work since the batch job is in upstream-dxp and has `elasticsearch.jdk11.enabled == true` set.

**Comment by joshchong** [comment]
@brookedalton Ideally we wouldn't want to remove the portal.upstream property from the poshi test since that both communicates that the test is running upstream and also gives us control over whether we want to remove it from upstream in the future.

So let's try this instead.

Set the test poshi property to:
`property portal.upstream = "jdk11";`

Then set the test.properties PQL to:
```
test.batch.run.property.query[functional-tomcat90-mysql57-jdk11_open][upstream-dxp]=\
         (portal.upstream == jdk11)
```
Don't make any changes to the jdk8 batch PQL.

This prevents the test from running on any other non-jdk11 batch and also gives people the option to expand the jdk11 batch in the future while still allowing for the granularity of running jdk11 only tests.
E.g. they could do something like
```
        (\
            (portal.upstream == quarantine) OR \
            (portal.upstream == true) OR \
            (portal.upstream == jdk11)\
        )
```

When testing just scope to the jdk11 batch.

**Comment by brookedalton** [comment]
ci:forward

**Pull request closed without merging**
